/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_rmanage (void)
{
    GtkWidget *rmanage;
    GtkWidget *vbox1;
    GtkWidget *menubar1;
    GtkWidget *menuitem1;
    GtkWidget *menu1;
    GtkWidget *new1;
    GtkWidget *open1;
    GtkWidget *save1;
    GtkWidget *save_as1;
    GtkWidget *separatormenuitem1;
    GtkWidget *quit1;
    GtkWidget *menuitem2;
    GtkWidget *menu2;
    GtkWidget *cut1;
    GtkWidget *copy1;
    GtkWidget *paste1;
    GtkWidget *delete1;
    GtkWidget *menuitem3;
    GtkWidget *menu3;
    GtkWidget *menuitem4;
    GtkWidget *menu4;
    GtkWidget *about1;
    GtkWidget *hbox2;
    GtkWidget *scrolledwindow1;
    GtkWidget *nictree;
    GtkWidget *vbox8;
    GtkWidget *detect;
    GtkWidget *about;
    GtkWidget *quit;
    GtkWidget *image3;
    GtkAccelGroup *accel_group;

    accel_group = gtk_accel_group_new ();

    rmanage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_widget_set_size_request (rmanage, 900, 300);
    gtk_window_set_title (GTK_WINDOW (rmanage), _("Rmanage"));

    vbox1 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox1);
    gtk_container_add (GTK_CONTAINER (rmanage), vbox1);

    menubar1 = gtk_menu_bar_new ();
    gtk_widget_show (menubar1);
    gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

    menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
    gtk_widget_show (menuitem1);
    gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

    menu1 = gtk_menu_new ();
    gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menu1);

    new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
    gtk_widget_show (new1);
    gtk_container_add (GTK_CONTAINER (menu1), new1);

    open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
    gtk_widget_show (open1);
    gtk_container_add (GTK_CONTAINER (menu1), open1);

    save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
    gtk_widget_show (save1);
    gtk_container_add (GTK_CONTAINER (menu1), save1);

    save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
    gtk_widget_show (save_as1);
    gtk_container_add (GTK_CONTAINER (menu1), save_as1);

    separatormenuitem1 = gtk_separator_menu_item_new ();
    gtk_widget_show (separatormenuitem1);
    gtk_container_add (GTK_CONTAINER (menu1), separatormenuitem1);
    gtk_widget_set_sensitive (separatormenuitem1, FALSE);

    quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
    gtk_widget_show (quit1);
    gtk_container_add (GTK_CONTAINER (menu1), quit1);

    menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
    gtk_widget_show (menuitem2);
    gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

    menu2 = gtk_menu_new ();
    gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menu2);

    cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
    gtk_widget_show (cut1);
    gtk_container_add (GTK_CONTAINER (menu2), cut1);

    copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
    gtk_widget_show (copy1);
    gtk_container_add (GTK_CONTAINER (menu2), copy1);

    paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
    gtk_widget_show (paste1);
    gtk_container_add (GTK_CONTAINER (menu2), paste1);

    delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
    gtk_widget_show (delete1);
    gtk_container_add (GTK_CONTAINER (menu2), delete1);

    menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
    gtk_widget_show (menuitem3);
    gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

    menu3 = gtk_menu_new ();
    gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menu3);

    menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
    gtk_widget_show (menuitem4);
    gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

    menu4 = gtk_menu_new ();
    gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

    about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
    gtk_widget_show (about1);
    gtk_container_add (GTK_CONTAINER (menu4), about1);

    hbox2 = gtk_hbox_new (FALSE, 0);
    gtk_widget_show (hbox2);
    gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

    scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
    gtk_widget_show (scrolledwindow1);
    gtk_box_pack_start (GTK_BOX (hbox2), scrolledwindow1, TRUE, TRUE, 0);
    gtk_widget_set_size_request (scrolledwindow1, 672, 272);

    nictree = gtk_tree_view_new ();
    gtk_widget_show (nictree);
    gtk_container_add (GTK_CONTAINER (scrolledwindow1), nictree);

    vbox8 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox8);
    gtk_box_pack_start (GTK_BOX (hbox2), vbox8, TRUE, TRUE, 0);

    detect = gtk_button_new_from_stock ("gtk-find");
    gtk_widget_show (detect);
    gtk_box_pack_start (GTK_BOX (vbox8), detect, FALSE, FALSE, 0);

    about = gtk_button_new_from_stock ("gtk-about");
    gtk_widget_show (about);
    gtk_box_pack_start (GTK_BOX (vbox8), about, FALSE, FALSE, 0);

    quit = gtk_button_new_from_stock ("gtk-quit");
    gtk_widget_show (quit);
    gtk_box_pack_start (GTK_BOX (vbox8), quit, FALSE, FALSE, 0);

    image3 = gtk_image_new_from_stock ("gtk-network", GTK_ICON_SIZE_DIALOG);
    gtk_widget_show (image3);
    gtk_box_pack_start (GTK_BOX (vbox8), image3, TRUE, TRUE, 0);
    gtk_widget_set_size_request (image3, 102, 48);

    g_signal_connect ((gpointer) rmanage, "delete_event",
                      G_CALLBACK (on_rmanage_delete_event),
                      NULL);
    g_signal_connect ((gpointer) rmanage, "destroy_event",
                      G_CALLBACK (on_rmanage_destroy_event),
                      NULL);
    g_signal_connect ((gpointer) rmanage, "destroy",
                      G_CALLBACK (on_rmanage_destroy),
                      NULL);
    g_signal_connect ((gpointer) new1, "activate",
                      G_CALLBACK (on_new1_activate),
                      NULL);
    g_signal_connect ((gpointer) open1, "activate",
                      G_CALLBACK (on_open1_activate),
                      NULL);
    g_signal_connect ((gpointer) save1, "activate",
                      G_CALLBACK (on_save1_activate),
                      NULL);
    g_signal_connect ((gpointer) save_as1, "activate",
                      G_CALLBACK (on_save_as1_activate),
                      NULL);
    g_signal_connect ((gpointer) quit1, "activate",
                      G_CALLBACK (on_quit1_activate),
                      NULL);
    g_signal_connect ((gpointer) cut1, "activate",
                      G_CALLBACK (on_cut1_activate),
                      NULL);
    g_signal_connect ((gpointer) copy1, "activate",
                      G_CALLBACK (on_copy1_activate),
                      NULL);
    g_signal_connect ((gpointer) paste1, "activate",
                      G_CALLBACK (on_paste1_activate),
                      NULL);
    g_signal_connect ((gpointer) delete1, "activate",
                      G_CALLBACK (on_delete1_activate),
                      NULL);
    g_signal_connect ((gpointer) about1, "activate",
                      G_CALLBACK (on_about1_activate),
                      about1);
    g_signal_connect ((gpointer) nictree, "row_activated",
                      G_CALLBACK (on_nictree_row_activated),
                      NULL);
    g_signal_connect ((gpointer) detect, "clicked",
                      G_CALLBACK (on_detect_clicked),
                      nictree);
    g_signal_connect ((gpointer) about, "clicked",
                      G_CALLBACK (on_about_clicked),
                      NULL);
    g_signal_connect ((gpointer) quit, "clicked",
                      G_CALLBACK (on_quit_clicked),
                      NULL);

    /* Store pointers to all widgets, for use by lookup_widget(). */
    GLADE_HOOKUP_OBJECT_NO_REF (rmanage, rmanage, "rmanage");
    GLADE_HOOKUP_OBJECT (rmanage, vbox1, "vbox1");
    GLADE_HOOKUP_OBJECT (rmanage, menubar1, "menubar1");
    GLADE_HOOKUP_OBJECT (rmanage, menuitem1, "menuitem1");
    GLADE_HOOKUP_OBJECT (rmanage, menu1, "menu1");
    GLADE_HOOKUP_OBJECT (rmanage, new1, "new1");
    GLADE_HOOKUP_OBJECT (rmanage, open1, "open1");
    GLADE_HOOKUP_OBJECT (rmanage, save1, "save1");
    GLADE_HOOKUP_OBJECT (rmanage, save_as1, "save_as1");
    GLADE_HOOKUP_OBJECT (rmanage, separatormenuitem1, "separatormenuitem1");
    GLADE_HOOKUP_OBJECT (rmanage, quit1, "quit1");
    GLADE_HOOKUP_OBJECT (rmanage, menuitem2, "menuitem2");
    GLADE_HOOKUP_OBJECT (rmanage, menu2, "menu2");
    GLADE_HOOKUP_OBJECT (rmanage, cut1, "cut1");
    GLADE_HOOKUP_OBJECT (rmanage, copy1, "copy1");
    GLADE_HOOKUP_OBJECT (rmanage, paste1, "paste1");
    GLADE_HOOKUP_OBJECT (rmanage, delete1, "delete1");
    GLADE_HOOKUP_OBJECT (rmanage, menuitem3, "menuitem3");
    GLADE_HOOKUP_OBJECT (rmanage, menu3, "menu3");
    GLADE_HOOKUP_OBJECT (rmanage, menuitem4, "menuitem4");
    GLADE_HOOKUP_OBJECT (rmanage, menu4, "menu4");
    GLADE_HOOKUP_OBJECT (rmanage, about1, "about1");
    GLADE_HOOKUP_OBJECT (rmanage, hbox2, "hbox2");
    GLADE_HOOKUP_OBJECT (rmanage, scrolledwindow1, "scrolledwindow1");
    GLADE_HOOKUP_OBJECT (rmanage, nictree, "nictree");
    GLADE_HOOKUP_OBJECT (rmanage, vbox8, "vbox8");
    GLADE_HOOKUP_OBJECT (rmanage, detect, "detect");
    GLADE_HOOKUP_OBJECT (rmanage, about, "about");
    GLADE_HOOKUP_OBJECT (rmanage, quit, "quit");
    GLADE_HOOKUP_OBJECT (rmanage, image3, "image3");

    gtk_window_add_accel_group (GTK_WINDOW (rmanage), accel_group);

    return rmanage;
}

GtkWidget*
create_About (void)
{
    GtkWidget *About;
    GtkWidget *dialog_vbox1;
    GtkWidget *fixed2;
    GtkWidget *scrolledwindow2;
    GtkWidget *viewport1;
    GtkWidget *vbox2;
    GtkWidget *pre;
    GtkWidget *image2;
    GtkWidget *post;
    GtkWidget *dialog_action_area1;
    GtkWidget *about_ok;

    About = gtk_dialog_new ();
    gtk_window_set_title (GTK_WINDOW (About), _("About"));
    gtk_window_set_type_hint (GTK_WINDOW (About), GDK_WINDOW_TYPE_HINT_DIALOG);

    dialog_vbox1 = GTK_DIALOG (About)->vbox;
    gtk_widget_show (dialog_vbox1);

    fixed2 = gtk_fixed_new ();
    gtk_widget_show (fixed2);
    gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed2, TRUE, TRUE, 0);

    scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
    gtk_widget_show (scrolledwindow2);
    gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow2, 0, 0);
    gtk_widget_set_size_request (scrolledwindow2, 328, 200);

    viewport1 = gtk_viewport_new (NULL, NULL);
    gtk_widget_show (viewport1);
    gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport1);

    vbox2 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox2);
    gtk_container_add (GTK_CONTAINER (viewport1), vbox2);

    pre = gtk_label_new (_("RManage A network monitoring\nand management tool."));
    gtk_widget_show (pre);
    gtk_box_pack_start (GTK_BOX (vbox2), pre, FALSE, FALSE, 0);
    gtk_label_set_justify (GTK_LABEL (pre), GTK_JUSTIFY_CENTER);

    image2 = gtk_image_new_from_stock ("gtk-network", GTK_ICON_SIZE_DIALOG);
    gtk_widget_show (image2);
    gtk_box_pack_start (GTK_BOX (vbox2), image2, TRUE, TRUE, 0);
    gtk_widget_set_size_request (image2, -1, 0);

    post = gtk_label_new (_("developed by Ashok Shankar Das\nashok.s.das@gmail.com\nVersion 0.1.7"));
    gtk_widget_show (post);
    gtk_box_pack_start (GTK_BOX (vbox2), post, FALSE, FALSE, 0);
    gtk_label_set_justify (GTK_LABEL (post), GTK_JUSTIFY_CENTER);

    dialog_action_area1 = GTK_DIALOG (About)->action_area;
    gtk_widget_show (dialog_action_area1);
    gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

    about_ok = gtk_button_new_from_stock ("gtk-ok");
    gtk_widget_show (about_ok);
    gtk_dialog_add_action_widget (GTK_DIALOG (About), about_ok, GTK_RESPONSE_OK);
    GTK_WIDGET_SET_FLAGS (about_ok, GTK_CAN_DEFAULT);

    g_signal_connect ((gpointer) about_ok, "clicked",
                      G_CALLBACK (on_about_ok_clicked),
                      About);

    /* Store pointers to all widgets, for use by lookup_widget(). */
    GLADE_HOOKUP_OBJECT_NO_REF (About, About, "About");
    GLADE_HOOKUP_OBJECT_NO_REF (About, dialog_vbox1, "dialog_vbox1");
    GLADE_HOOKUP_OBJECT (About, fixed2, "fixed2");
    GLADE_HOOKUP_OBJECT (About, scrolledwindow2, "scrolledwindow2");
    GLADE_HOOKUP_OBJECT (About, viewport1, "viewport1");
    GLADE_HOOKUP_OBJECT (About, vbox2, "vbox2");
    GLADE_HOOKUP_OBJECT (About, pre, "pre");
    GLADE_HOOKUP_OBJECT (About, image2, "image2");
    GLADE_HOOKUP_OBJECT (About, post, "post");
    GLADE_HOOKUP_OBJECT_NO_REF (About, dialog_action_area1, "dialog_action_area1");
    GLADE_HOOKUP_OBJECT (About, about_ok, "about_ok");

    return About;
}

GtkWidget*
create_netwindow (void)
{
    GtkWidget *netwindow;
    GtkWidget *scrolledwindow3;
    extern GtkWidget *nodetree;

    netwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_widget_set_size_request (netwindow, 512, 256);
    gtk_window_set_title (GTK_WINDOW (netwindow), _("nodes"));

    scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
    gtk_widget_show (scrolledwindow3);
    gtk_container_add (GTK_CONTAINER (netwindow), scrolledwindow3);
    gtk_widget_set_size_request (scrolledwindow3, 512, 256);

    nodetree = gtk_tree_view_new ();
    gtk_widget_show (nodetree);
    gtk_container_add (GTK_CONTAINER (scrolledwindow3), nodetree);
    gtk_widget_set_size_request (nodetree, 512, 256);

    g_signal_connect ((gpointer) netwindow, "destroy",
                      G_CALLBACK (on_netwindow_destroy),
                      NULL);
    g_signal_connect ((gpointer) netwindow, "delete_event",
                      G_CALLBACK (on_netwindow_delete_event),
                      NULL);
    g_signal_connect ((gpointer) nodetree, "row_activated",
                      G_CALLBACK (on_nodetree_row_activated),
                      NULL);

    /* Store pointers to all widgets, for use by lookup_widget(). */
    GLADE_HOOKUP_OBJECT_NO_REF (netwindow, netwindow, "netwindow");
    GLADE_HOOKUP_OBJECT (netwindow, scrolledwindow3, "scrolledwindow3");
    GLADE_HOOKUP_OBJECT (netwindow, nodetree, "nodetree");

    return netwindow;
}

GtkWidget*
create_Command (void)
{
    GtkWidget *Command;
    GtkWidget *scrolledwindow4;
    GtkWidget *viewport2;
    GtkWidget *vbox3;
    GtkWidget *hbox1;
    GtkWidget *vbox5;
    GtkWidget *username;
    GtkWidget *vbox4;
    GtkWidget *username_entry;
    GtkWidget *vbox6;
    GtkWidget *passwd;
    GtkWidget *vbox7;
    GtkWidget *passwd_entry;
    GtkWidget *scrolledwindow5;
    extern GtkWidget *prototree;

    Command = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_window_set_title (GTK_WINDOW (Command), _("Command"));

    scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
    gtk_widget_show (scrolledwindow4);
    gtk_container_add (GTK_CONTAINER (Command), scrolledwindow4);
    gtk_widget_set_size_request (scrolledwindow4, 512, 256);

    viewport2 = gtk_viewport_new (NULL, NULL);
    gtk_widget_show (viewport2);
    gtk_container_add (GTK_CONTAINER (scrolledwindow4), viewport2);

    vbox3 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox3);
    gtk_container_add (GTK_CONTAINER (viewport2), vbox3);

    hbox1 = gtk_hbox_new (FALSE, 0);
    gtk_widget_show (hbox1);
    gtk_box_pack_start (GTK_BOX (vbox3), hbox1, TRUE, TRUE, 0);

    vbox5 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox5);
    gtk_box_pack_start (GTK_BOX (hbox1), vbox5, TRUE, TRUE, 0);

    username = gtk_label_new (_("User Name"));
    gtk_widget_show (username);
    gtk_box_pack_start (GTK_BOX (vbox5), username, FALSE, FALSE, 0);

    vbox4 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox4);
    gtk_box_pack_start (GTK_BOX (hbox1), vbox4, FALSE, FALSE, 0);

    username_entry = gtk_entry_new ();
    gtk_widget_show (username_entry);
    gtk_box_pack_start (GTK_BOX (vbox4), username_entry, FALSE, FALSE, 0);
    gtk_entry_set_invisible_char (GTK_ENTRY (username_entry), 8226);

    vbox6 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox6);
    gtk_box_pack_start (GTK_BOX (hbox1), vbox6, TRUE, TRUE, 0);

    passwd = gtk_label_new (_("Passwd"));
    gtk_widget_show (passwd);
    gtk_box_pack_start (GTK_BOX (vbox6), passwd, FALSE, FALSE, 0);

    vbox7 = gtk_vbox_new (FALSE, 0);
    gtk_widget_show (vbox7);
    gtk_box_pack_start (GTK_BOX (hbox1), vbox7, TRUE, TRUE, 0);

    passwd_entry = gtk_entry_new ();
    gtk_widget_show (passwd_entry);
    gtk_box_pack_start (GTK_BOX (vbox7), passwd_entry, FALSE, FALSE, 0);
    gtk_entry_set_invisible_char (GTK_ENTRY (passwd_entry), 8226);

    scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
    gtk_widget_show (scrolledwindow5);
    gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow5, TRUE, TRUE, 0);
    gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

    prototree = gtk_tree_view_new ();
    gtk_widget_show (prototree);
    gtk_container_add (GTK_CONTAINER (scrolledwindow5), prototree);
    gtk_widget_set_size_request (prototree, -1, 240);

    g_signal_connect ((gpointer) prototree, "row_activated",
                      G_CALLBACK (on_prototree_row_activated),
                      Command);

    /* Store pointers to all widgets, for use by lookup_widget(). */
    GLADE_HOOKUP_OBJECT_NO_REF (Command, Command, "Command");
    GLADE_HOOKUP_OBJECT (Command, scrolledwindow4, "scrolledwindow4");
    GLADE_HOOKUP_OBJECT (Command, viewport2, "viewport2");
    GLADE_HOOKUP_OBJECT (Command, vbox3, "vbox3");
    GLADE_HOOKUP_OBJECT (Command, hbox1, "hbox1");
    GLADE_HOOKUP_OBJECT (Command, vbox5, "vbox5");
    GLADE_HOOKUP_OBJECT (Command, username, "username");
    GLADE_HOOKUP_OBJECT (Command, vbox4, "vbox4");
    GLADE_HOOKUP_OBJECT (Command, username_entry, "username_entry");
    GLADE_HOOKUP_OBJECT (Command, vbox6, "vbox6");
    GLADE_HOOKUP_OBJECT (Command, passwd, "passwd");
    GLADE_HOOKUP_OBJECT (Command, vbox7, "vbox7");
    GLADE_HOOKUP_OBJECT (Command, passwd_entry, "passwd_entry");
    GLADE_HOOKUP_OBJECT (Command, scrolledwindow5, "scrolledwindow5");
    GLADE_HOOKUP_OBJECT (Command, prototree, "prototree");

    return Command;
}

