/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
GtkWidget *nodetree;
GtkWidget *prototree;
GtkWidget* create_rmanage (void);
GtkWidget* create_About (void);
GtkWidget* create_netwindow (void);
GtkWidget* create_Command (void);
